dist: xenial
language: ruby
rvm:
  - 2.5.1
env:
  - COVERAGE=yes
services:
  - docker
before_install:
  - gem install bundler -v 1.16.1
install:
    - docker-compose -f ./spec/docker-compose.yml up -d --build
    - docker exec spec_puppet_1 puppetserver ca generate --certname aceserver \
                              --subject-alt-names 'localhost,aceserver,ace_aceserver_1,
                              spec_puppetserver_1,ace_server,puppet_server,
                              spec_aceserver_1,puppetdb,spec_puppetdb_1,0.0.0.0,
                              puppet,spec_puppet_1,ace_aceserver_1'
    - docker-compose -f ./docker-compose.yml up -d --build