version: '3'

services:
  puppet:
    hostname: puppet
    container_name: spec_puppet_1
    build: .
    ports:
      - 8140:8140
    environment:
      - DNS_ALT_NAMES=puppet,localhost,aceserver,ace_aceserver_1,spec_puppetserver_1,ace_server,puppet_server,spec_aceserver_1,puppetdb,spec_puppetdb_1,0.0.0.0
      - PUPPETDB_SERVER_URLS=https://puppetdb:8081
    volumes:
      - ./volumes/puppet:/etc/puppetlabs/puppet/
      - ./volumes/serverdata:/opt/puppetlabs/server/data/puppetserver/

  postgres:
    container_name: spec_postgres_1
    environment:
      - POSTGRES_PASSWORD=puppetdb
      - POSTGRES_USER=puppetdb
      - POSTGRES_DB=puppetdb
    expose:
      - 5432
    image: postgres:9.6
    volumes:
      - ./volumes/puppetdb-postgres/data:/var/lib/postgresql/data/
      - ./postgres-custom:/docker-entrypoint-initdb.d

  puppetdb:
    hostname: puppetdb
    container_name: spec_puppetdb_1
    image: puppet/puppetdb
    environment:
      - PUPPETDB_PASSWORD=puppetdb
      - PUPPETDB_USER=puppetdb
    ports:
      - 32775:8080
      - 32776:8081
    depends_on:
      - postgres
      - puppet
    volumes:
      - ./volumes/puppetdb/ssl:/etc/puppetlabs/puppet/ssl/

networks:
  default:
